version: '3.6'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=metastore_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - LANG=C.UTF-8
    volumes:
      - ./_script/docker-mysql/conf/:/etc/mysql/conf.d
      - ./_script/docker-mysql/sql/:/docker-entrypoint-initdb.d
    command: --sql_mode=''
    security_opt:
      - seccomp:unconfined

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin12345
    volumes:
      - ./_volume/docker-minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  hive-metastore:
    container_name: hive-metastore
    build:
      context: _dockerfile/docker-metastore
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        sleep 10;
        /entrypoint.sh
    ports:
      - "9083:9083"
    depends_on:
      - mysql
