version: '3.6'
services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./_script/docker-spark/apps:/opt/spark-apps
      - ./_script/docker-spark/data:/opt/spark-data
      - ./_script/docker-spark/conf:/spark/conf
      - /tmp/spark-events-local:/tmp/spark-events
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./_script/docker-spark/apps:/opt/spark-apps
      - ./_script/docker-spark/data:/opt/spark-data
      - ./_script/docker-spark/conf:/spark/conf
      - /tmp/spark-events-local:/tmp/spark-events
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:

    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./_script/docker-spark/apps:/opt/spark-apps
      - ./_script/docker-spark/data:/opt/spark-data
      - ./_script/docker-spark/conf:/spark/conf
      - /tmp/spark-events-local:/tmp/spark-events
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-history-server:
    image: bde2020/spark-history-server:3.1.1-hadoop3.2
    container_name: spark-history-server
    depends_on:
      - spark-master
    ports:
      - "18081:18081"
    volumes:
      - ./_script/docker-spark/apps:/opt/spark-apps
      - ./_script/docker-spark/data:/opt/spark-data
      - ./_script/docker-spark/conf:/spark/conf
      - /tmp/spark-events-local:/tmp/spark-events
  storage-postgres:
    image: postgres:11.7-alpine
    container_name: storage-postgers
    depends_on:
      - spark-master
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root