version: '3.6'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=pipeline
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    volumes:
      - ./_script/docker-mysql/conf/:/etc/mysql/conf.d
      - ./_script/docker-mysql/sql/:/docker-entrypoint-initdb.d
    command: --sql_mode=''

  redis:
    image: redis:5
    container_name: redis
    restart: always
    command: redis-server # --requirepass credential
    ports:
      - 6379:6379

